export default {
  CREATE_SUCCESS: "CREATE_SUCCESS",
  CREATE_SUCCESS_SUCCESS: "CREATE_SUCCESS_SUCCESS",
  CREATE_FAIL: "CREATE_FAIL",
  CREATE_FAIL_SUCCESS: "CREATE_FAIL_SUCCESS",
  CREATE_LOADING: "CREATE_LOADING",
  CREATE_LOADING_SUCCESS: "CREATE_LOADING_SUCCESS",
  RESET_TOAST: "RESET_TOAST",
  RESET_TOAST_SUCCESS: "RESET_TOAST_SUCCESS",
  REMOVE_TOAST: "REMOVE_TOAST",
  REMOVE_TOAST_SUCCESS: "REMOVE_TOAST_SUCCESS",
};
