export default {
  CREATE_REVIEW: "CREATE_REVIEW",
  CREATE_REVIEW_SUCCESS: "CREATE_REVIEW_SUCCESS",
  CREATE_REVIEW_FAILED: "CREATE_REVIEW_FAILED",
  DESTROY_REVIEW: "DESTROY_REVIEW",
  DESTROY_REVIEW_SUCCESS: "DESTROY_REVIEW_SUCCESS",
  DESTROY_REVIEW_FAILED: "DESTROY_REVIEW_FAILED",
};
