export default {
  CREATE_COMMENT: "CREATE_COMMENT",
  CREATE_COMMENT_SUCCESS: "CREATE_COMMENT_SUCCESS",
  CREATE_COMMENT_FAILED: "CREATE_COMMENT_FAILED",
  GET_ALL_COMMENT: "GET_ALL_COMMENT",
  GET_ALL_COMMENT_SUCCESS: "GET_ALL_COMMENT_SUCCESS",
  GET_ALL_COMMENT_FAILED: "GET_ALL_COMMENT_FAILED",
  DESTROY_COMMENT: "DESTROY_COMMENT",
  DESTROY_COMMENT_SUCCESS: "DESTROY_COMMENT_SUCCESS",
  DESTROY_COMMENT_FAILED: "DESTROY_COMMENT_FAILED",
};
