export default {
  GET_ALL_ITEM: "GET_ALL_ITEM",
  GET_ALL_ITEM_SUCCESS: "GET_ALL_ITEM_SUCCESS",
  GET_ALL_ITEM_FAILED: "GET_ALL_ITEM_FAILED",
  GET_ONE_ITEM: "GET_ONE_ITEM",
  GET_ONE_ITEM_SUCCESS: "GET_ONE_ITEM_SUCCESS",
  GET_ONE_ITEM_FAILED: "GET_ONE_ITEM_FAILED",
  SEARCH_ITEM: "SEARCH_ITEM",
  SEARCH_ITEM_SUCCESS: "SEARCH_ITEM_SUCCESS",
};
