export default {
  GET_ALL_ITEM: "GET_ALL_ITEM",
  GET_ALL_ITEM_SUCCESS: "GET_ALL_ITEM_SUCCESS",
  GET_ALL_ITEM_FAILED: "GET_ALL_ITEM_FAILED",
  GET_ONE_ITEM: "GET_ONE_ITEM",
  GET_ONE_ITEM_SUCCESS: "GET_ONE_ITEM_SUCCESS",
  GET_ONE_ITEM_FAILED: "GET_ONE_ITEM_FAILED",

  ADD_TO_BASKET: "ADD_TO_BASKET",
  REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
};
